/**
 * Material 3 design tokens: type scale, shape, elevation, state-layer
 * opacities, and motion. Values are the M3 baseline spec defaults; the
 * `motion.duration` scale is a 3-tier simplification of the official
 * short1-4/medium1-4/long1-4 scale (documented in docs/design/m3-tokens.md).
 *
 * Color roles live in `m3-theme.css` (generated by
 * scripts/generate-m3-theme.ts), not here — colors are consumed as CSS
 * custom properties, not TS values, so they can flow through
 * `prefers-color-scheme` without a JS runtime dependency.
 */

export interface TypescaleStyle {
  fontSize: string;
  lineHeight: string;
  fontWeight: number;
  letterSpacing: string;
}

export const typescale = {
  displayLarge: { fontSize: "57px", lineHeight: "64px", fontWeight: 400, letterSpacing: "-0.25px" },
  displayMedium: { fontSize: "45px", lineHeight: "52px", fontWeight: 400, letterSpacing: "0px" },
  displaySmall: { fontSize: "36px", lineHeight: "44px", fontWeight: 400, letterSpacing: "0px" },
  headlineLarge: { fontSize: "32px", lineHeight: "40px", fontWeight: 400, letterSpacing: "0px" },
  headlineMedium: { fontSize: "28px", lineHeight: "36px", fontWeight: 400, letterSpacing: "0px" },
  headlineSmall: { fontSize: "24px", lineHeight: "32px", fontWeight: 400, letterSpacing: "0px" },
  titleLarge: { fontSize: "22px", lineHeight: "28px", fontWeight: 400, letterSpacing: "0px" },
  titleMedium: { fontSize: "16px", lineHeight: "24px", fontWeight: 500, letterSpacing: "0.15px" },
  titleSmall: { fontSize: "14px", lineHeight: "20px", fontWeight: 500, letterSpacing: "0.1px" },
  bodyLarge: { fontSize: "16px", lineHeight: "24px", fontWeight: 400, letterSpacing: "0.5px" },
  bodyMedium: { fontSize: "14px", lineHeight: "20px", fontWeight: 400, letterSpacing: "0.25px" },
  bodySmall: { fontSize: "12px", lineHeight: "16px", fontWeight: 400, letterSpacing: "0.4px" },
  labelLarge: { fontSize: "14px", lineHeight: "20px", fontWeight: 500, letterSpacing: "0.1px" },
  labelMedium: { fontSize: "12px", lineHeight: "16px", fontWeight: 500, letterSpacing: "0.5px" },
  labelSmall: { fontSize: "11px", lineHeight: "16px", fontWeight: 500, letterSpacing: "0.5px" },
} as const satisfies Record<string, TypescaleStyle>;

export type TypescaleKey = keyof typeof typescale;

export const shape = {
  none: "0px",
  extraSmall: "4px",
  small: "8px",
  medium: "12px",
  large: "16px",
  extraLarge: "28px",
  full: "9999px",
} as const;

export const elevation = {
  0: "none",
  1: "0 1px 2px 0 rgba(0, 0, 0, 0.3), 0 1px 3px 1px rgba(0, 0, 0, 0.15)",
  2: "0 1px 2px 0 rgba(0, 0, 0, 0.3), 0 2px 6px 2px rgba(0, 0, 0, 0.15)",
  3: "0 1px 3px 0 rgba(0, 0, 0, 0.3), 0 4px 8px 3px rgba(0, 0, 0, 0.15)",
  4: "0 1px 3px 0 rgba(0, 0, 0, 0.3), 0 6px 10px 4px rgba(0, 0, 0, 0.15)",
  5: "0 1px 3px 0 rgba(0, 0, 0, 0.3), 0 8px 12px 6px rgba(0, 0, 0, 0.15)",
} as const;

export const stateLayer = {
  hover: 0.08,
  focus: 0.1,
  pressed: 0.1,
  dragged: 0.16,
} as const;

export const motion = {
  easing: {
    standard: "cubic-bezier(0.2, 0, 0, 1)",
    emphasized: "cubic-bezier(0.3, 0, 0.8, 0.15)",
  },
  duration: {
    short: "150ms",
    medium: "300ms",
    long: "500ms",
  },
} as const;

export const m3 = { typescale, shape, elevation, stateLayer, motion } as const;
