import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

/** Spec base names @ai-km/api-client knows how to generate, in a stable order. */
export const SPEC_NAMES = ["core", "auth", "conversations", "transcriptions", "analytics"];

const GENERATED_HEADER = "/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n";

/**
 * Real codegen for one spec file: contracts/openapi/<name>.yaml -> .d.ts source text.
 * Passed as a file:// URL (not raw text) because some specs (e.g. auth.yaml) `$ref`
 * schemas defined in a sibling spec file (core.yaml) — resolving that cross-file ref
 * needs openapi-typescript's own URL-based resolver.
 */
export async function defaultGenerateOne(specPath) {
  const ast = await openapiTS(pathToFileURL(specPath));
  return GENERATED_HEADER + astToString(ast);
}

/**
 * Generate `src/generated/<name>.d.ts` for every spec present under `specDir`.
 * Specs listed in `specNames` that don't exist on disk are skipped and reported
 * in `missing` instead of failing the run (contracts land incrementally).
 */
export async function runGenerate({
  specDir,
  outDir,
  specNames = SPEC_NAMES,
  generateOne = defaultGenerateOne,
}) {
  mkdirSync(outDir, { recursive: true });
  const generated = [];
  const missing = [];
  for (const name of specNames) {
    const specPath = path.join(specDir, `${name}.yaml`);
    if (!existsSync(specPath)) {
      missing.push(name);
      continue;
    }
    const content = await generateOne(specPath);
    writeFileSync(path.join(outDir, `${name}.d.ts`), content);
    generated.push(name);
  }
  return { generated, missing };
}

const isMain = process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url;
if (isMain) {
  const scriptsDir = path.dirname(fileURLToPath(import.meta.url));
  const packageRoot = path.resolve(scriptsDir, "..");
  const { generated, missing } = await runGenerate({
    specDir: path.resolve(packageRoot, "../../contracts/openapi"),
    outDir: path.resolve(packageRoot, "src/generated"),
  });
  console.log(`[api-client generate] generated: ${generated.join(", ") || "(none)"}`);
  if (missing.length > 0) {
    console.warn(`[api-client generate] skipped missing spec(s): ${missing.join(", ")}`);
  }
  process.exit(0);
}
