#!/usr/bin/env node
/**
 * Generates `src/m3-theme.css` — static, committed M3 light/dark color
 * scheme CSS custom properties — from a single seed color. No network
 * access; runtime has zero dependency on this script.
 *
 * Usage:
 *   pnpm --filter @ai-km/design-tokens generate   # (re)writes src/m3-theme.css
 *   pnpm --filter @ai-km/design-tokens check       # fails if output would differ
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { Hct, SchemeTonalSpot, argbFromHex, hexFromArgb } from "@material/material-color-utilities";
import { M3_COLOR_ROLES, kebabToCamel, cssVarForRole, type M3ColorRole } from "../src/m3-roles";

/** Confirmed by user 2026-08-28 (see docs/stories/PENDING_DECISIONS.md). */
export const SEED_COLOR = "#1e56a0";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = path.resolve(__dirname, "../src/m3-theme.css");

type SchemeRecord = Record<string, number>;

function buildScheme(isDark: boolean) {
  const sourceHct = Hct.fromInt(argbFromHex(SEED_COLOR));
  return new SchemeTonalSpot(sourceHct, isDark, 0, "2021");
}

export function roleHex(scheme: SchemeRecord, role: M3ColorRole): string {
  const value = scheme[kebabToCamel(role)];
  if (typeof value !== "number") {
    throw new Error(`DynamicScheme has no role "${role}"`);
  }
  return hexFromArgb(value);
}

/** All M3 color roles resolved to hex for a given light/dark mode — used by generation and tests alike. */
export function getSchemeHexMap(isDark: boolean): Record<M3ColorRole, string> {
  const scheme = buildScheme(isDark) as unknown as SchemeRecord;
  const entries = M3_COLOR_ROLES.map((role) => [role, roleHex(scheme, role)] as const);
  return Object.fromEntries(entries) as Record<M3ColorRole, string>;
}

function renderRoleBlock(scheme: SchemeRecord, indent: string): string {
  return M3_COLOR_ROLES.map((role) => `${indent}${cssVarForRole(role)}: ${roleHex(scheme, role)};`).join("\n");
}

export function generateCss(): string {
  const light = buildScheme(false) as unknown as SchemeRecord;
  const dark = buildScheme(true) as unknown as SchemeRecord;

  return `/**
 * AUTO-GENERATED by packages/design-tokens/scripts/generate-m3-theme.ts — do not edit by hand.
 * Regenerate: pnpm --filter @ai-km/design-tokens generate
 * Verify no drift: pnpm --filter @ai-km/design-tokens check
 * Seed color: ${SEED_COLOR} (user-confirmed 2026-08-28, see docs/stories/PENDING_DECISIONS.md)
 * Source: @material/material-color-utilities SchemeTonalSpot, spec 2021, contrastLevel 0
 */

:root {
${renderRoleBlock(light, "  ")}
}

@media (prefers-color-scheme: dark) {
  :root {
${renderRoleBlock(dark, "    ")}
  }
}
`;
}

function main() {
  const checkOnly = process.argv.includes("--check");
  const generated = generateCss();

  if (checkOnly) {
    if (!existsSync(OUTPUT_PATH)) {
      console.error(`m3-theme.css does not exist at ${OUTPUT_PATH}. Run "generate" first.`);
      process.exit(1);
    }
    const existing = readFileSync(OUTPUT_PATH, "utf8");
    if (existing !== generated) {
      console.error("m3-theme.css is out of date. Run: pnpm --filter @ai-km/design-tokens generate");
      process.exit(1);
    }
    console.log("m3-theme.css is up to date.");
    return;
  }

  writeFileSync(OUTPUT_PATH, generated, "utf8");
  console.log(`Wrote ${OUTPUT_PATH}`);
}

const isMainModule = process.argv[1] === fileURLToPath(import.meta.url);
if (isMainModule) {
  main();
}
