import { readFileSync } from "node:fs";

const DEFAULT_OWNER_FILE_PATH = "/data/python/AI_KM-worktrees/.e2e.owner";
const PID_PATTERN = /\bpid=(\d+)\b/;

export type IsProcessAlive = (pid: number) => boolean;

/**
 * `process.kill(pid, 0)` sends no signal — it only asks the OS whether
 * `pid` exists and is reachable. `ESRCH` means the process is gone
 * (dead); `EPERM` means it exists but is owned by someone else (still
 * alive, just not ours to signal) — either way that is "alive" for our
 * purposes, since we only care about "gone" vs "not gone".
 */
function isProcessAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    return (error as NodeJS.ErrnoException).code === "EPERM";
  }
}

export interface LockGuardOptions {
  /** Defaults to AI_KM_E2E_OWNER_FILE, then the real shared `.e2e.owner` path. */
  ownerFilePath?: string;
  /** Defaults to AI_KM_E2E_LOCK_TOKEN. */
  lockToken?: string;
  /** Test-only injection point — production always uses the real `process.kill(pid, 0)` check. */
  isProcessAliveOverride?: IsProcessAlive;
}

/**
 * E04-S057. `.e2e.lock`'s flock guarantees mutual exclusion only between
 * wrapper scripts that go through it — it does nothing to stop a
 * completely unguarded `playwright test` invocation (a bare `pnpm test`
 * at repo root fans out into `@ai-km/e2e:test` via turbo, with zero lock
 * awareness) from running concurrently against whatever a legitimate lock
 * holder's `next dev`/`apps/api` servers already have listening —
 * `resolveReuseExistingServer()` is `true` on every local machine, so
 * Playwright silently ADOPTS those servers instead of failing to bind.
 * Two independent test suites then drive the same servers at once, and
 * neither one's results can be trusted. This is exactly what corrupted
 * W1's E01-S022 rerun on 2026-08-29 (docs/stories/E04-S057.md).
 *
 * Call this at `playwright.config.ts` module-eval time, the same
 * synchronous phase `ensureFakeMicrophoneWav()`/`assertPortsFreeForCI()`
 * already run in — every entry point (`playwright test`, `--list`,
 * `--last-failed`, a turbo-triggered run) evaluates that module first, so
 * a single check there covers all of them.
 *
 * "Am I the lock holder" is proven by an exact match against a per-
 * acquisition TOKEN, not the human-readable `.e2e.owner` line itself —
 * that line's label/timestamp can legitimately be re-worded or
 * re-generated by the same holder without the underlying acquisition
 * changing, and comparing the full line would then make the holder block
 * itself (the single worst failure mode here, since it only surfaces
 * inside the lock). The reference wrapper (`e2e-locked.sh`) generates one
 * token per acquisition, writes it to `<ownerFilePath>.token`, and
 * exports the SAME value as `AI_KM_E2E_LOCK_TOKEN` for every process it
 * spawns.
 *
 * A `.e2e.owner` naming a PID that is no longer running is a stale claim
 * left by a crashed run, not a live hold — treated the same as "no
 * owner" (AC4), with a warning, rather than a hard block. `.e2e.owner` is
 * a courtesy/coordination file; the real mutual exclusion is `flock`
 * itself. Hard-failing on a stale file would let one crash deadlock every
 * lane until someone manually deletes it — a worse outcome than the
 * (pre-existing, unrelated to this change) brief window where a stale
 * file could be misleading. Aligned with E04-S056/W3 on this point.
 *
 * An owner line whose `pid=` field can't even be parsed fails CLOSED
 * (blocks) instead — that is genuine uncertainty, not a proven-stale
 * claim, and this story's whole premise is that uncertainty here must
 * never resolve to "silently proceed."
 */
export function assertNotBlockingLockHolder(options: LockGuardOptions = {}): void {
  const ownerFilePath = options.ownerFilePath ?? process.env.AI_KM_E2E_OWNER_FILE ?? DEFAULT_OWNER_FILE_PATH;
  const lockToken = options.lockToken ?? process.env.AI_KM_E2E_LOCK_TOKEN;
  const checkAlive = options.isProcessAliveOverride ?? isProcessAlive;

  let ownerLine: string;
  try {
    ownerLine = readFileSync(ownerFilePath, "utf8").trim();
  } catch {
    return; // AC4: no owner file -> nobody holds the lock -> proceed.
  }
  if (ownerLine.length === 0) return;

  const pidMatch = PID_PATTERN.exec(ownerLine);
  if (!pidMatch) {
    throw new Error(
      `[E04-S057] Refusing to start Playwright: ${ownerFilePath} exists but its content ` +
        `("${ownerLine}") doesn't match the expected "... pid=<n> ..." format, so this ` +
        `process cannot confirm whether the recorded holder is still running. Treating an ` +
        `unparseable claim as live rather than risking a silent double-run. If this file is ` +
        `genuinely stale, remove it (and its .token sibling) manually.`,
    );
  }

  const ownerPid = Number(pidMatch[1]);
  if (!checkAlive(ownerPid)) {
    console.warn(
      `[E04-S057] ${ownerFilePath} names pid ${ownerPid}, which is no longer running — ` +
        `treating this as a stale claim from a crashed run, not a live lock, and proceeding.`,
    );
    return;
  }

  let holderToken: string | undefined;
  try {
    holderToken = readFileSync(`${ownerFilePath}.token`, "utf8").trim();
  } catch {
    holderToken = undefined;
  }

  if (lockToken && holderToken && lockToken === holderToken) {
    return; // AC3: this process IS the recorded lock holder.
  }

  throw new Error(
    `[E04-S057] Refusing to start Playwright: the shared E2E lock is currently held by ` +
      `someone else (${ownerFilePath} names "${ownerLine}"), and this process is not them. ` +
      `Running unguarded here would let Playwright's reuseExistingServer silently attach to ` +
      `their dev servers and corrupt their measurement (this is exactly what happened to ` +
      `W1's E01-S022 rerun on 2026-08-29). Wait for the lock to free, or run this inside the ` +
      `same flock-protected wrapper that set AI_KM_E2E_LOCK_TOKEN (see e2e-locked.sh).`,
  );
}
